# Generated by Django 3.0.8 on 2020-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
