# Generated by Django 3.0.8 on 2020-08-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ammount',
            new_name='amount',
        ),
    ]
